### ISSUE TITLE
Invalid node version

### ISSUE THREAD

**Issue by aggieSzulcDornach** [TonyDeplanque/strapi-plugin-migrations#12]
After upgrading Strapi which has:
 `"engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },`
I updated node version to `18.13.0`.
This is no longer compatible with the plugin's node version ` "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },`.
Do you foresee a fix for this?

**Comment by MatthiasD0** [comment]
@TonyDeplanque this would be cool

**Comment by tailn804** [comment]
I have the same problem, Node version 17.9.1 don't run strapi-plugin-migrations.

**Comment by obafunmiso-olufemi** [comment]
You probably want to use `patch-package` to bump the node version till this [PR](https://github.com/TonyDeplanque/strapi-plugin-migrations/pull/14) is merged
